name: Build Jekyll site
on:
 push:
   branches: ["deploy"]
permissions:
  contents: read
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Build
        uses: actions/jekyll-build-pages@v1
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
  deploy:
    runs-on: ubuntu-latest
    needs: build
    env:
        SSHPASS: ${{ secrets.SSH_PASSWORD }}
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: github-pages
      - name: Deploy to server
        id: deployment
        run: |
            sshpass -e scp -o StrictHostKeyChecking=no artifact.tar ${{ secrets.SSH_USER }}@www2.hu-berlin.de:
            cat artifact.tar | sshpass -e ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@www2.hu-berlin.de "tar --no-overwrite-dir -xmvf -"
    environment:
      name: production
    #   url: ${{ steps.deployment.outputs.page_url }}